stages:
  - Test
  - Release
  - TestRelease

Compare repls:
  stage: Test
  image:
    name: debian:bullseye
  variables:
    RENODE_VERSION: "latest"
    DEBIAN_FRONTEND: "noninteractive"
    GET_CUSTOM_RENODE_REVISION: ""
  artifacts:
    paths:
      - ci-output/repls
      - ci-output/robot-results
      - ci-output/regressions
    when: always
  before_script:
    - apt -qqy update > /dev/null 2> /dev/null
    - apt -qqy install automake autoconf cmake libtool g++ coreutils policykit-1 libgtk2.0-dev uml-utilities gtk-sharp2 wget jq git curl python3 python3-pip parallel xz-utils rename > /dev/null 2> /dev/null
    - apt -qqy install mono-complete 2> /dev/null > /dev/null
    - mono --version
    - ./ci/prepare.sh
  script:
    - ./ci/test.sh
    - ./ci/process_test_results.sh

Static release:
  stage: Release
  image:
    name: debian:bullseye
  before_script:
    - apt -qqy update > /dev/null 2> /dev/null
    - apt -qqy install patchelf build-essential python3-pip zlib1g-dev > /dev/null 2> /dev/null
    - pip3 install pyinstaller staticx
  script:
    - pip3 install requests -t deps
    - echo >> dts2repl/__init__.py
    - echo "version_commit ='${CI_COMMIT_SHORT_SHA}'" >> dts2repl/__init__.py
    - echo "version_additional = 'static'" >> dts2repl/__init__.py
    - pyinstaller --onefile dts2repl/dts2repl.py --paths deps --add-data dts2repl/models.json:. --add-data dts2repl/overlay:overlay
    - staticx dist/dts2repl dts2repl-static
    - chmod +x dts2repl-static
    - cp dist/dts2repl dts2repl-dynamic
    - chmod +x dts2repl-dynamic    
  artifacts:
    paths:
      - dts2repl-static
      - dts2repl-dynamic

Test Static release:
  stage: TestRelease
  image:
    name: debian:bullseye
  dependencies: [Static release]    
  script:
    - ./dts2repl-static https://zephyr-samples-builder.storage.googleapis.com/zephyr/063ce9caf54fa656f02ae48f3c9d537659a10dec/96b_aerocore2/hello_world/hello_world.dts --output test.repl
    - apt -qqy update > /dev/null 2> /dev/null
    - apt -qqy --no-install-recommends install wget ca-certificates > /dev/null 2> /dev/null
    - wget https://zephyr-samples-builder.storage.googleapis.com/zephyr/063ce9caf54fa656f02ae48f3c9d537659a10dec/96b_aerocore2/hello_world/hello_world.dts
    - ./dts2repl-static --version
    - ./dts2repl-static hello_world.dts --output test2.repl
    - diff test.repl test2.repl || true
    - cat test.repl
  artifacts:
    paths:
      - test.repl
      - test2.repl
